// <auto-generated />
namespace CallCenter.API.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddFacebookMessageIdColumnInMessages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFacebookMessageIdColumnInMessages));
        
        string IMigrationMetadata.Id
        {
            get { return "201706272016583_AddFacebookMessageIdColumnInMessages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
